### ISSUE TITLE
Option to include all subtitles

### ISSUE THREAD

**Issue by ahnooie** [ahnooie/automatic-ripping-machine#34]
Option to add all subtitles to the mkv file -- but still make the "forced" one default (not sure if this is even possible).

**Comment by RandomNinjaAtk** [comment]
The Pull request for MakeMKV profiles would enable this... You have to customize the "default.mmcp.xml" files profile for selection of audio/subtitles to make it work... Specifically, Line 18 is the line that needs to be modified. I use a custom one like this "-sel:all,+sel:(eng|nolang),+sel:special,-sel:havelossless,+sel:(core|havemulti),-sel:mvcvideo,=100:all,-10:eng,=0:lossless,=1:multi".

This way I have lossless audio, more information on customizing it is here: http://www.makemkv.com/forum2/viewtopic.php?f=10&t=4386

**Comment by muckngrind4** [comment]
On the handbrake side, this can be accomplished with my last PR.  Looks like @RandomNingaAtk has it covered through MakeMKV.

@ahnooie , I'll let you close this once you've reviews the PRs.

**Comment by muckngrind4** [comment]
I think this is resolved with the last couple of PR's.  I'll close it.  We can reopen if needed.
