### ISSUE TITLE
Low Quality Artwork For Music

### ISSUE THREAD

**Issue by RandomNinjaAtk** [ahnooie/automatic-ripping-machine#42]
So I've attempted to solve this myself with no luck, but the artwork that is acquired at the time of ripping a CD is like 250x250 in size. When viewing on a 55" 4k/1080p display, it really doesn't look good. It's better right now to just disable the artwork and let the tools like Plex/Emby to download them for me.

I would prefer to have the artwork grabbed at the time of the rip, but it really needs to be a minimum of 800x800... 1000x1000 resolution would be preferable.

**Comment by ahnooie** [comment]
Are there any options in .abcde?  If not @muckngrind4 added the ability to make an API call to Emby to tell it to do a library rescan once a video rip completes, there's no reason we couldn't do something similar post audio cd rip.  Would that work?

**Comment by RandomNinjaAtk** [comment]
http://www.andrews-corner.org/linux/abcde/getalbumart.html

I've tried implementing part of that guide, cause it seems possible. But I was only able to achieve resizing the small image to a desired size. Which wasn't the desired result, but maybe I wasn't reading or implementing it correctly...

**Comment by ahnooie** [comment]
I think the best we can do is #26 where Emby can be configured to scan the library post fix.  I'm going to go ahead and close this, but if you can think of a better way to do this we can re-open it.
