### ISSUE TITLE
root user used for everything

### ISSUE THREAD

**Issue by gsantner** [ahnooie/automatic-ripping-machine#43]
The root user is used for everything in here, including some rm and `rm -rf` commands. Please also do note that in the README. Run commands with as few as possible rights, e.g. with own user `arm`.

**Comment by RandomNinjaAtk** [comment]
From talking/working with @ahnooie the only way he was able to make the script work was to run it as the root user. I helped make a lot of changes to add additional functionality, but I don't have the experience or expertise make the changes required resolve your request. If you have ideas or know how to make it work without running as root, I think we'd all appreciate it. Pull requests are welcome! :D

**Comment by gsantner** [comment]
I personally couldn't get this working, sorry^^
As above - would recommend to note this in the readme.
I personally don't have a spare device with disc reader currently to try this on an other machine. 
This script crashed at some points (sent to mbox), and unmounted some other things. I just don't want to kill the system just to try this, hope you can understand this. (BTW: /var/log/ doesn't have any log of ARM so I can't supply more informations.

**Comment by ahnooie** [comment]
I agree, ultimately it shouldn't run as root but until it can run as a normal user (as @RandomNinjaAtk said a PR with this change would be great) a warning in the README is a good idea.

I thunk udev calls the script as root so probably the armwrapper could su to another user, I'm not sure if HandBrake or MakeMKV need anything special to run as a normal account.

@gsantner logs are in /opt/arm/logs--hopefully they'll be in /var/log someday.

**Comment by gsantner** [comment]
First let us sum up:

* MakeMKV - I used it yesterday with the GUI - I didn't add any root password, so I think it should work without root; Needs right to write in target directory.
* Handbrake - needs right to write in target directory; need read right to source 
* Notifications - Don't need root - 100%
* .... (will be added as EDIT)

**Comment by RandomNinjaAtk** [comment]
From a clean install of Ubuntu, I had no problems getting it to work with only following the directions. I don't think were trying to argue that the individual tools don't work without using root. I think its a problem for having the script to auto-recognize the disc and kick the process off that is requiring the need  to run it as root.

The one thing I can think of to resolve it, is there needs to be a Terminal Command that can be used to kickstart the process, then you just have a cron-job to run that process at a set interval, which will then allow it to run as the user. So the Terminal Command would execute the script every 10 or 15 minutes to check for the Disc and begin to process it.

For an example, this script that has similar features accomplishes that: http://docs.jcode.me/autorippr/

I've seen other scripts do it that, but I don't have the experience or expertise to re-architect it that way...

PR welcome! :D
