### ISSUE TITLE
Help: Handbrake is now installed through flatpaks on Ubuntu.

### ISSUE THREAD

**Issue by dbuttric** [ahnooie/automatic-ripping-machine#458]
### Description
I have to make some dramatic changes to how HandBrakeCLI is invoked through the handbrake.py script. 
### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
 Ubuntu 18.04.6
### Log file
no rip successful yet, due to changes in invocation for HandBrakeCLI.

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by dbuttric** [comment]
Well, I tried to rewrite the frontend to HandbrakeCLI, and while I got close i failed. I think my problems are output redirection, but I'm not sure.
I am not running Handbrake 1.2.1 installed on the OS.
I will continue to work on this, but may give up.

**Comment by 1337-server** [comment]
What is it you're trying to do ?

**Comment by dbuttric** [comment]
I'm running Ubuntu 18.04, and I want the latest version of Handbrake. It looks like I have to either install a flatpak, or build from source.
I'm trying to build from sourcce right now. It's been many years since I ran ./configure, so it's taking me a while.
I want to run the latest software, to get performance benefits. 
I'm hoping that I can get Handbrake to use Intel Quickstep.
Thanks.
