### ISSUE TITLE
arm_wrapper.sh failed with exit code 1 on Ubuntu 16.10

### ISSUE THREAD

**Issue by jharder01** [ahnooie/automatic-ripping-machine#47]
Looking for some guidance here. I'm putting the disk in (Bluray and DVD) and not getting anything except errors in various log files. 
Ubuntu 16.10
Attempted with USB Bluray drive and SATA dvd-rw drive but getting same results on both devices
Installed per README instruction
After inserting disk, I see the following error in /var/log/syslog (often it will show the failed with exit code 1 twice in a row).
```
syslog: systemd-udevd[8698]: Process '/opt/arm/arm_wrapper.sh' failed with exit code 1.
```
If I manually trigger arm_wrapper.sh as root, I get the following message:
```
root@docker:/opt/arm# ./arm_wrapper.sh
warning: commands will be executed using /bin/sh
job 5 at Wed Feb  8 15:43:00 2017
```
I also receive mail (body below)
```
/opt/arm/config
device node not found
/opt/arm/identify.sh: line 109: ((: > 0 : syntax error: operand expected (error token is "> 0 ")
eject: tried to use `/dev/' as device name but it is no block device
eject: tried to use `/media/' as device name but it is no block device
eject: tried to use `/mnt/' as device name but it is no block device
eject: tried to use `./' as device name but it is no block device
eject: unable to find or open device for: `'

```
Output of /opt/arm/logs/empty.log after manually kicking off arm_wrapper.sh
```
*** Start config parameters ****
ARM_CHECK_UDF=true
GET_VIDEO_TITLE=true
SKIP_TRANSCODE=false
RAWPATH="/mnt/media/ARM/raw/"
MEDIA_DIR="/mnt/media/ARM/Media/Movies/"
LOGPATH="/opt/arm/logs/"
LOGLIFE=1
SET_MEDIA_PERMISSIONS=false
CHMOD_VALUE=777
MINLENGTH="600"
RIPMETHOD="mkv"
MKV_ARGS=""
HB_PRESET="High Profile"
DEST_EXT=mkv
HANDBRAKE_CLI=HandBrakeCLI
MAINFEATURE=false
HB_ARGS="--subtitle scan -F"
PLEX_SUPPORT=true
EMBY_REFRESH=false
EMBY_SUBFOLDERS=true
EMBY_SERVER=""
EMBY_PORT="8096"
EMBY_CLIENT="ARM"
EMBY_DEVICE="ARM"
EMBY_DEVICEID="ARM"
EMBY_USERNAME=""
EMBY_USERID=""
IFTTT_EVENT="arm_event"
LOG=$LOGPATH$LOGFILE
*** End config parameters ****
Starting Identify Script...
Deleting 0 old log files:
unable to identify


*** Start config parameters ****
ARM_CHECK_UDF=true
GET_VIDEO_TITLE=true
SKIP_TRANSCODE=false
RAWPATH="/mnt/media/ARM/raw/"
MEDIA_DIR="/mnt/media/ARM/Media/Movies/"
LOGPATH="/opt/arm/logs/"
LOGLIFE=1
SET_MEDIA_PERMISSIONS=false
CHMOD_VALUE=777
MINLENGTH="600"
RIPMETHOD="mkv"
MKV_ARGS=""
HB_PRESET="High Profile"
DEST_EXT=mkv
HANDBRAKE_CLI=HandBrakeCLI
MAINFEATURE=false
HB_ARGS="--subtitle scan -F"
PLEX_SUPPORT=true
EMBY_REFRESH=false
EMBY_SUBFOLDERS=true
EMBY_SERVER=""
EMBY_PORT="8096"
EMBY_CLIENT="ARM"
EMBY_DEVICE="ARM"
EMBY_DEVICEID="ARM"
EMBY_USERNAME=""
EMBY_USERID=""
IFTTT_EVENT="arm_event"
LOG=$LOGPATH$LOGFILE
*** End config parameters ****
Starting Identify Script...
Deleting 0 old log files:
unable to identify
```

**Comment by ahnooie** [comment]
udev sets environment variables before the arm_wrapper.sh script is called so it can't be called directly.

If you insert a disc instead of calling the script manually are there any logs produced under /opt/arm/logs/?

I don't know of anyone who has tried it on 16.10 so that may be the issue, do you have the option to run it on 16.04?

**Comment by techprowizard** [comment]
just chiing in. i'm having the same issue as well. my system is also running 16.10 (never ran 16.04) and back in december this did work. i'm getting nothing in the /opt/arm/logs/ folder. the only indication of an error is the
/var/log/syslog
systemd-udevd[24270]: Process '/opt/arm/arm_wrapper.sh' failed with exit code 1.

**Comment by ahnooie** [comment]
Thanks, I'll start a 16.10 download and see if I can reproduce the issue there, it's still working fine for me on 16.04.

**Comment by jharder01** [comment]
Ahnooie,
I spun up a 16.04 VM and the ARM software seems to be working fine on that platform. 

In respect to 16.10; I see the same results as techprowizard.

**Comment by techprowizard** [comment]
don't know if this will be of any help, but there may be an issue with the  `| at now `  part of the arm_wrapper.sh
i changed udev log priority to debug
`sudo udevadm control --log-priority=debug`
and when testing i found this line
`Feb 19 12:36:34 ubuntu systemd-udevd[28872]: '/opt/arm/arm_wrapper.sh'(err) 'Cannot open lockfile /var/spool/cron/atjobs/.SEQ: Read-only file system'`
i tried removing `| at now` to see what that would do. it appears to launch arm_wrapper.sh, but nothing else happens, not even an empty.log.
don't know if any of this is useful, but thought i'd report what i found.

**Comment by ahnooie** [comment]
Thanks, @techprowizard   Can you confirm that "at" is installed (sudo apt install at).  If so, it might be an issue with bash and at on Ubuntu 16.10.  Try changing the first line of the arm_wrapper.sh script from #!/bin/bash to #!/bin/sh and see if that helps.

**Comment by techprowizard** [comment]
`at` is installed and unfortunately changing to #!/bin/sh changes nothing.

**Comment by ahnooie** [comment]
Well, I got 16.10 installed and I can duplicate the issue but no idea how to fix it yet, it appears to be caused by changes in systemd / udev.  Might have to change the ARM to run as a service or find some other way around it.

**Comment by techprowizard** [comment]
Ok. i did some digging and research and found a way to make it work. here's what i did.

in `arm_wrapper.sh`

change


`#!/bin/bash`
`echo bash /opt/arm/identify.sh /opt/arm/config | at now`

to 

`#!/bin/bash`
`{`
`echo bash /opt/arm/identify.sh /opt/arm/config | at now`
`} &`

then run
`sudo nano /lib/systemd/system/udev.service`
and change the line
`ConditionPathIsReadWrite=/sys`
to
`ConditionPathIsReadWrite=/`

the run the commands
`sudo service udev restart`
`sudo systemctl daemon-reload`
`sudo udevadm control --reload-rules`


The only issue i have now is that if the drive is empty it will still eject the disc tray.

**Comment by ahnooie** [comment]
Thanks for doing the legwork @techprowizard that should be enough info for anyone wanting it to run on 16.10 to get it working.  On 16.04 the disc does not eject when empty, at least not on my system.  I think my position on the interim Ubuntu releases is I just don't have time to support them.  udev / systemd is such a moving target on the interim releases I can't keep up, I could get it working with 16.10 but then it would probably break again for 17.04.  I'll plan on supporting only LTS releases since they're stable.  However, that said, if someone wants to do a PR to make it work on interim releases like 16.10 without breaking 16.04 I'll be happy to merge it in.  I hope that sounds reasonable.
