### ISSUE TITLE
Support for Pushover notifications

### ISSUE THREAD

**Issue by sco01** [ahnooie/automatic-ripping-machine#50]
I really like the Pushbullet and IFTTT notifications. Pushover.net is another popular notification service. 

My proposal:

Add the following config parameters:

```
# Pushover API User and Application Key
# Leave User key empty or comment out to disable Pushover notifications
PO_USER_KEY="<User key>"
PO_APP_KEY="<application key>"
```

Add the following to notify.sh:

```
#Notification via Pushover
#Trigger onl if variable is set
if [ -z "$PO_USER_KEY" ]; then
        echo "Pusover notifications not enabled" >> "$LOG"
else
        echo "Sending Pushover notification" >> "$LOG"
        curl -s --form-string "token=$PO_APP_KEY"  --form-string "user=$PO_USER_KEY" --form-string "message=$MSG" https://api.pushover.net/1/messages.json
        echo "Pushover notification sent" >> "$LOG"
fi
```

More info available here: https://pushover.net/faq#library-shell

**Comment by ahnooie** [comment]
I think this look good, would you mind doing a pull request for this?

**Comment by sco01** [comment]
I would like to but I'm not a developer and I have basically no knowledge in using git beyond cloning a repo.

**Comment by ahnooie** [comment]
NP, I'll add it next time I get a chance.

**Comment by ahnooie** [comment]
Added Pushover support @sco01.  Let me know if you have any trouble with it.
