### ISSUE TITLE
Feature Request: Log audio rips individually rather than in "empty.log"

### ISSUE THREAD

**Issue by cbunt1** [ahnooie/automatic-ripping-machine#63]
Currently, all audio cd rips are logged in the empty.log file. This makes it difficult to troubleshoot individual cd-rips when performing simultaneous processes, and it prevents audio-cd rip logs from being flushed in the standard log cleaning process.

I am working on a feature enhancement to create the individual log files for audio rips with roughly the same methodology used for video rips. Implementation checks for the required tools (abcde-musicbrainz-tool and.or cd-discid) with a failover to the existing methodology. Current preference is for a Musicbrainz ID, but either methodology is functional, and serves the purpose.

**Comment by ahnooie** [comment]
Merged in your PR #64
