### ISSUE TITLE
Log / Notification Doesn't Include Title Name

### ISSUE THREAD

**Issue by neil-bowers** [ahnooie/automatic-ripping-machine#85]
While working with ARM today, I found that the log only contains the title for the MakeMKV portion of the job, and not for the HandBrakeCLI/transcode portion.

The variable `${ID_FS_LABEL}` is used to contain the title name and is used in several scripts - `video_rip.sh`, `video_transcode.sh` - and while it's usage in `video_rip.sh` does result in the title being included in the log message, it doesn't when used in `video_transcode.sh` - I'm not sure if this is because the variable is becoming unset between one script and the next or what - I'm rather new to shell scripting.

It's not a breaking inconsistency, just triggers a bit of OCD :-)

**Comment by audioeng** [comment]
I have just submitted PR #86 to fix this behavior, using the LABEL variable which is used extensively already in this script and is the same as the directory the files are placed in, instead of ID_FS_LABEL.

Very simple fix that has all my notifications working perfectly.

**Comment by neil-bowers** [comment]
Pretty much what I had done on my local copy.  I'll take your changes and merge them in as it doesn't appear that ahnooie is doing much atm.

**Comment by audioeng** [comment]
I’ve been thinking about making the same change to the video rip
notification, as the ID_FS_LABEL is terrible on most old DVDs.
