### ISSUE TITLE
Logic inside config file

### ISSUE THREAD

**Issue by audioeng** [ahnooie/automatic-ripping-machine#89]
There is an if statement at the end of the config file, what is the purpose of that and can it be moved elsewhere? Generally you wouldn't want a config file to contain business logic, only variables and values.

In trying to parse the config file using Python everything I have tried is choking on this if logic.
I don't know enough about bash scripting to know, but I know that all I have ever seen is an empty.log file so I am wondering if this is running for anyone?

```
# Determine logfile name
# use the label of the DVD/CD or else use empty.log
# this is required for udev events where there is no media available
# such as ejecting the drive

if [ -n "$ID_FS_LABEL" ]; then
        LOGFILE=${ID_FS_LABEL}".log"
        elif [[ -n "$ID_CDROM_MEDIA_TRACK_COUNT_AUDIO" && $(which abcde-musicbrainz-tool) ]]; then
                LOGFILE=$(abcde-musicbrainz-tool --device "$DEVNAME" | cut -f1 -d ' ')".log"
        elif [[ -n "$ID_CDROM_MEDIA_TRACK_COUNT_AUDIO" &&  $(which cd-discid) ]]; then
                LOGFILE=$(cd-discid "$DEVNAME" | cut -f1 -d ' ')".log"
else
        LOGFILE="empty.log"
fi

# Set full logfile path
LOG=$LOGPATH$LOGFILE
```

**Comment by audioeng** [comment]
I was able to work around this by only grabbing the lines with the variable assignment I need instead of the entire config file.

**Comment by audioeng** [comment]
While not ideal to have logic in a config file, if no one else is concerned and I have worked around it reading from python, we can close this.

**Comment by ahnooie** [comment]
I think this is a valid issue, logic should be somewhere else.  Thanks.

**Comment by audioeng** [comment]
Since it looks like it is dealing with naming the file differently for audio cds, this might be better placed int he identity.sh script. However, I just want to do a sanity check to make sure this logic is actually working? I ask because I have ripped all the different type and the only log file I have ever seen written to is empty.log

Is anyone else getting different log files? If not, we might just be able to remove it and just set the name. If so, we can find a better place I think.

**Comment by audioeng** [comment]
Interestingly, I copied the whole log section of the config file to identify.sh just after it reads the config and the first DVD I inserted logged some stuff to empty.log and then created a logfile for the disc, something I have never witnessed before! It didn't log a bunch of stuff during the rip process (all the MKV stuff went to empty.log) but it was something...

**Comment by audioeng** [comment]
Ok, I think I see how to make this work, the $LOG variable is being passed to the rip scripts, but it isn't being used, and I didn't yet comment out the parts of the config file that set it, so it is being set back to empty.log on each of these scripts.

I can't start on this now, but I think this should be a pretty straight forward PR, I'll try to get started on this soon. This should accomplish two things, get the logic out of the config file and get the separate log files per disc working correctly.
