### ISSUE TITLE
Auto grab MakeMKV app_key

### ISSUE THREAD

**Issue by physk** [ahnooie/automatic-ripping-machine#91]
## NOT AN ISSUE
I've created a little script that will grab the latest app_key from the MakeMKV Forum and update the MakeMKV config file with it.

[mmkvcode](https://github.com/physk/mmkvcode)

All instructions needed are on that page / README file.

Feel free to try it out, Any issues let me know either here or create an issue on the repo 👍

**Comment by audioeng** [comment]
Cool idea, but I really feel that if you are using the shareware features(Blu-ray ripping) of MakeMKV, you should be purchasing the registration key. You don't need a key for the freeware functions (DVD ripping)

The key in the MKV Forum is intended for beta testers of MakeMKV, not to extend the 30 day demo period indefinitely. If you are using the beta version with ARM and contributing feedback to MakeMKV then by all means use this script to make that process easier for you.

**Comment by ahnooie** [comment]
I don't think it's an issue to automate it while they provide a free key, but I'd rather see people buy a key if MakeMKV is useful.  I purchased a key and would encourage others to do the same.  (I would have used open source software for this piece, but I couldn't find anything even remotely comparable).
