### ISSUE TITLE
Raw files deleted?

### ISSUE THREAD

**Issue by KeppensJonas** [ahnooie/automatic-ripping-machine#99]
Are the raw files removed automatically?

**Comment by audioeng** [comment]
Yes, unless you manually cancel a batched job or the server reboots due to power failure.

**Comment by KeppensJonas** [comment]
Is it possible to change the config so that the raw files will be not removed?

**Comment by audioeng** [comment]
Not the config, but if you wanted source files not to be deleted following a video transcode, you would edit the video_transcode.sh, commenting out any lines that start rm or rmdir and end with “$SRC”

There are several.

**Comment by KeppensJonas** [comment]
Okay, thank you
